protected/models/Firma.php
<?php

/**
 * This is the model class for table "firma".
 *
 * The followings are the available columns in table 'firma':
 * @property string $id
 * @property string $naziv
 * @property string $adresa
 * @property string $telefon
 */
class Firma extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'firma';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('naziv, adresa, telefon', 'required'),
			array('naziv, adresa, telefon', 'length', 'max'=>100),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, naziv, adresa, telefon', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
                    'makler'=>array(self::HAS_MANY,"Makler",'idfirma'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'naziv' => Yii::t("main","NAZIV"),
			'adresa' => Yii::t("main","ADRESA"),
			'telefon' => Yii::T("main","TELEFON"),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('naziv',$this->naziv,true);
		$criteria->compare('adresa',$this->adresa,true);
		$criteria->compare('telefon',$this->telefon,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Firma the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/FirmaController.php
<?php

class FirmaController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
                     array('allow',  'actions'=>array('PDF'),'users'=>array('*')),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','report'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
public function actionPDF(){
	$this->renderPartial('report');
    }
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Firma;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Firma']))
		{
			$model->attributes=$_POST['Firma'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Firma']))
		{
			$model->attributes=$_POST['Firma'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Firma');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}


	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Firma('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Firma']))
			$model->attributes=$_GET['Firma'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Firma the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Firma::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Firma $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='firma-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/firma/_form.php
<?php
/* @var $this FirmaController */
/* @var $model Firma */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'firma-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'naziv'); ?>
		<?php echo $form->textField($model,'naziv',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'naziv'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'adresa'); ?>
		<?php echo $form->textField($model,'adresa',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'adresa'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'telefon'); ?>
		<?php echo $form->textField($model,'telefon',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'telefon'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? Yii::t("main", "FIRMA_DODAJ") : Yii::t("main", "FIRMA_AZURIRAJ")); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/firma/_search.php
<?php
/* @var $this FirmaController */
/* @var $model Firma */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'naziv'); ?>
		<?php echo $form->textField($model,'naziv',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'adresa'); ?>
		<?php echo $form->textField($model,'adresa',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'telefon'); ?>
		<?php echo $form->textField($model,'telefon',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/firma/_view.php
<?php
/* @var $this FirmaController */
/* @var $data Firma */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('naziv')); ?>:</b>
	<?php echo CHtml::encode($data->naziv); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('adresa')); ?>:</b>
	<?php echo CHtml::encode($data->adresa); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('telefon')); ?>:</b>
	<?php echo CHtml::encode($data->telefon); ?>
	<br />


</div>

protected/views/firma/admin.php
<?php
/* @var $this FirmaController */
/* @var $model Firma */
Yii::setPathOfAlias("bootstrap",
Yii::getPathOfAlias('application.extensions.bootstrap'));

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#firma-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<?php $this->widget("bootstrap.widgets.TbButton",array(
		'buttonType'=>'link',
		'type'=>'primary',
		'size'=>'small',
		'label'=>Yii::t("main","FIRMA_DODAJ"),
		'url'=>array('firma/create'),
		'htmlOptions'=>array(
		'style'=>'margin-top:10px;'
)
));?>
<br>

<?php
 $this->widget('bootstrap.widgets.TbGridView',array(
     'id'=>'firma-grid',
     'dataProvider'=>$model->search(),
     'type'=>'bordered striped',
     'emptyText'=>  Yii::t("main", "NEMA_REZULTATA"),
     'filter'=>$model,
     'columns'=>array(
        'naziv',
         'adresa',
         'telefon',
         array(
             'class'=>'bootstrap.widgets.TbButtonColumn',
             'template'=>'{view}{update}{delete}',
             'deleteConfirmation'=>Yii::t("main","FIRMA_POTVRDA_BRISANJA"),
         'updateButtonLabel'=>Yii::t("main","AZURIRAJ"),
       'deleteButtonLabel'=>Yii::t("main","BRISANJE"),
        'viewButtonLabel'=>Yii::t("main","PREGLED"),
         )
     )
 ));
?>

protected/views/firma/create.php
<?php
/* @var $this FirmaController */
/* @var $model Firma */

$this->breadcrumbs=array(
	'Firmas'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Firma', 'url'=>array('index')),
	array('label'=>'Manage Firma', 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t("main", "FIRMA_DODAJ"); ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/firma/index.php
<?php
/* @var $this FirmaController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Firmas',
);

$this->menu=array(
	array('label'=>'Create Firma', 'url'=>array('create')),
	array('label'=>'Manage Firma', 'url'=>array('admin')),
);
?>

<h1>Firmas</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/firma/print.php
<?php

$datum1=Yii::app()->request->getQuery("datum1");
$datum2=Yii::app()->request->getQuery("datum2");
$id=Yii::app()->request->getQuery("id");
$hop=$list= Yii::app()->db->createCommand("Select * from firma where id=$id")->queryAll();
foreach ($hop as $key) {
	$nazivFirme=$key['naziv'];
	}
        $this->layout='pdf';
		$model=new Firma();
		$model->scenario="search";

		$model->attributes = array('id' => $id);
	    //$model->unsetAttributes();  
		$dataProvider=$model->search();
        
      $datum=date("Y-m-d");
	  
	 
    $mPDF1 = Yii::app()->ePdf->mpdf();
    $mPDF1->WriteHTML($this->render('report',array('dataProvider'=>$dataProvider),true));
    $racunPath='racun/'.$id.'-'.$datum.'.pdf';
    $mPDF1->Output($racunPath,"F"); 
 
     $racuni=new Racuni();
     $racuni->idfirma=$id;
     
     $racuni->datum=$datum;
     $racuni->lokacija=$id.'-'.$datum;
     $racuni->save();
     $this->redirect(Yii::app()->baseUrl.'/'.$racunPath);
?>

protected/views/firma/report.php
<table>
     <tr>
     <td>
     <img src="images/logo.png" width="144" height="107">
     </td>
<td style="text-align: center;font-size: 10px; vertical-align: top;width:200px;">INT d.o.o.  tahric@int-doo.com  <br>
ul. Zavnobih H15  <br>  
BiH - 77 000 Bihac  <br>
ID Nummer BiH:         4263611500004<br>
Steuer Nummer BiH:   263611500004<br>

</td>
<td style=" text-align: center; font-size: 10px; vertical-align:top; width:200px ">
    tahric@int-doo.com<br>
    trgic@int-doo.com<br>
    www.int-doo.com <br>
</td>
<td style=" text-align: center;font-size: 10px; vertical-align: top; width:200px; ">
    BH: 00387-37-222 431 <br>
    CH: 0041-79-244 80 64 <br>
    D: 0049-151-572 54435 <br>
</td>
</tr>
</table>

<br>

<p align="center">Rechnung</p>
<?php


$data=$dataProvider->getData();
$datum=date("d.m.Y");
?>
<p align="right"> Datum: <?php echo $datum; ?> <p>
Firme:<br>
<?php

foreach ($data as $key) {
    echo $key['naziv'].'<br>'.$key['adresa'].'<br>'.$key['telefon'];
    $id=$key['id'];
}

$datum1=Yii::app()->request->getQuery("datum1");
$datum2=Yii::app()->request->getQuery("datum2");
?>

<center>
<table  border="1" style="border-spacing: 0px;">
	<tr>
		<td width="50px">Pos.</td>
		<td width="350px">Beschreibung</td>
		<td width="150px" style="text-align: center;">Menge</td>
		<td width="150px" style="text-align: center;">Einzelpreis €</td>
		<td width="150px" style="text-align: center;">Gesamtpreis €</td>

	</tr>
<?php
$list= Yii::app()->db->createCommand("SELECT t.vrijeme as datum,w.cijena as cijena FROM `terminstatgefunden` s inner join terminbestitig b on s.idterminbestig=b.idterminbestitig inner join termin t on b.idtermin=t.idtermin inner join wiedervorlage w on t.idwiedervorlage=w.idwiedervorlage inner join makler_owns_termin mt on b.idtermin=mt.idtermin inner join makler m on mt.idmakler=m.idmakler where m.idfirma=$id and t.vrijeme between '$datum1' and '$datum2'")->queryAll();
$br=1;
$uk=0;
foreach($list as $item){
?>
	<tr>
		<td><?php echo $br; ?></td>
		<td>Maklertermin vom <?php 
        $date=$item['datum'];

		$d=date_format(date_create($date),"d.m.Y"); 
		echo $d;?></td>
		<td style="text-align: center;">1</td>
		<td style="text-align: center;"> <?php echo $item['cijena']; ?></td>
		<td style="text-align: center;"><?php echo $item['cijena']; ?></td>
		
	</tr>
<?php
$uk+=$item['cijena'];
$br++;
 } ?>
</table>
<br>
<p align="right"><?php echo "Gesamtsumme: ".$uk." €"; ?><p>
<p align="right"><?php echo "Endsumme: ".$uk." €"; ?><p><br>

</center>

protected/views/firma/update.php
<?php
/* @var $this FirmaController */
/* @var $model Firma */

$this->breadcrumbs=array(
	'Firmas'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Firma', 'url'=>array('index')),
	array('label'=>'Create Firma', 'url'=>array('create')),
	array('label'=>'View Firma', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Firma', 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t("main", "FIRMA_AZURIRAJ"); ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/firma/view.php
<?php
/* @var $this FirmaController */
/* @var $model Firma */
Yii::setPathOfAlias("bootstrap",
Yii::getPathOfAlias('application.extensions.bootstrap'));
$cs=Yii::app()->clientscript;
   $cs->registerScriptFile( Yii::app()->theme->baseUrl . '/js/bootstrap-dropdown.js', CClientScript::POS_END );
$this->breadcrumbs=array(
	'Firmas'=>array('index'),
	$model->id,
);
Yii::app()->bootstrap->registerDatepicker();
?>
<script>
  $(function() {
    $( "#datum1" ).datepicker({
    	dateFormat: 'yy-mm-dd'
    });

    $( "#datum2" ).datepicker({
    	dateFormat: 'yy-mm-dd'
    });
  });
  </script>
<h1><?php echo Yii::t("main", "FIRMA_PREGLED"); ?></h1>
<hr>

	
</form>
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'naziv',
		'adresa',
		'telefon',
	),
)); ?>
<h1><?php echo Yii::t("main","IZVJESTAJ"); ?></h1>
<form method="GET">
<table>
<tr>
	<td><?php echo Yii::t("main","OD"); ?></td>
	<td><input type="text" id="datum1" name="datum1" /></td>


	<td><?php echo Yii::t("main","DO"); ?></td>
	<td><input type="text" id="datum2" name="datum2"/></td>

	
	<td>
		<input type="submit" name="ispis" value="Print"/>
	</td>
</tr>
</table>
<?php
if(isset($_GET['ispis'])){
	$datum1=$_GET['datum1'];
	$datum2=$_GET['datum2'];
	$id=Yii::app()->request->getQuery('id');

	$this->renderPartial('print');
}
?>
<hr>
<h1><?php echo Yii::t("main","IZDANI_RACUNI"); ?></h1>
<?php
$id=Yii::app()->request->getQuery('id');
$izdati=Yii::app()->db->createCommand("select * from racuni r inner join firma f on r.idfirma=f.id where r.idfirma=$id order by r.datum desc")->queryAll();

foreach ($izdati as $key) {
	$d=date_format(date_create($key['datum']),'d.m.Y');
	?>

<a href="<?php echo Yii::app()->baseUrl; ?>/racun/<?php echo $key['lokacija'].'.pdf'; ?>" target="" >Download</a> <?php echo '  '.$key['naziv'].'  '; ?><?php echo '  '.$d.'<br> '; ?>
	<?php
}
?>