protected/controllers/TerminController.php
<?php

class TerminController extends Controller
{
	public $layout='//layouts/column2';
	
	public function filters()
	{
	
			return array(
					'accessControl', // perform access control for CRUD operations
					'postOnly + delete,create,cancel,confirm', // we only allow deletion via POST request
			);
	}
	public function accessRules()
	{
		return array(
			array(
					'allow',
					'actions'=>array('create','index','view','getTerminsForMakler'),
					'users'=>array('@')
		),
                    array(
					'allow',
					'actions'=>array('create','index','view','getTerminsForZaposlenik'),
					'users'=>array('@')
                       
		),
				array(
						'allow',
						'actions'=>array('assignMakler','ponistiMaklera'),
						'expression'=>array(Yii::app()->user,"isAdminOrPosrednik"),
                                
		),
                    array(
					'allow',
					'actions'=>array('create','index','view','getTermins','delete'),
					'users'=>array('@')
		),
				array(
						'allow',
						'actions'=>array('cancel','confirm','pomjeriTermin','delete'),
						'expression'=>  array($this,'hasModifficationActionsAccess'),
		),
				array(
						'deny',
						'users'=>array('*'),
		)
		);
	}
        public function actionPonistiMaklera($id)
                
        {
            $criteria=new CDbCriteria();
            $criteria->compare("idtermin", $id);
            $mot=  MaklerOwnsTermin::model()->find($criteria);
           if($mot->delete())
           {
               $response['success']=true;
           }
           else
           {
               $response['success']=false;
           }
           echo CJSON::encode($response);
        }
	public function hasModifficationActionsAccess($user,$rule)
	{
		if(isset($_POST['id']))
		{
			return TerminController::userIsAuthorOrAdmin($_POST['id']);
		}
                elseif (Yii::app()->request->getQuery("id")!=null) {
                return TerminController::userIsAuthorOrAdmin(Yii::app()->request->getQuery("id"));
            }
		else
		{
			return false;
		}
	}
	/*
	 * Method checks if current user is author termin or application 
	 * administrator.
	 */
	public static function userIsAuthorOrAdmin($idtermin)
	{
		$termin=Termin::model()->findByPk($idtermin);
		return $termin->currentUserIsAuthor() || Yii::app()->user->isAdmin();
		
	}
        public function actionDelete($id)
        {
            $termin=  Termin::model()->findByPk($id);
            $termin->idwiedervorlage0->delete();
        }
public function actionCreate()
{
	if(isset($_POST['Termin']))
	{
		$termin=new Termin('create');
		$termin->attributes=$_POST['Termin'];
		
		$termin->status="offen";
		if($termin->validate())
		{
		$termin->idwiedervorlage0->status="termin";
	
			$termin->save(false);
			$termin->idwiedervorlage0->save(false);
			echo CJSON::encode(array('status'=>'success'));
		}
		else
		{
			$error = CActiveForm::validate($termin);
			if($error!='[]')
				echo $error;
			Yii::app()->end();
				
		}
		
	}
}
public function actionIndex()
{
	$termin=new Termin('search');
	$termin->idwiedervorlage0=new Wiedervorlage('search');
        if(Yii::app()->user->isMakler())
        {
            $termin->scenario="UserIsMakler";
        }
	$termin->idwiedervorlage0->idstranke0=new Stranka('search');
	$termin->idwiedervorlage0->idkorisnik0=new Korisnik('search');
	if(isset($_GET['Termin']) && isset($_GET['Stranka']))
	{
            if(isset($_GET['Wiedervorlage']))
            {
                $termin->idwiedervorlage0->attributes=$_GET['Wiedervorlage'];
            }
		$termin->attributes=$_GET['Termin'];
                Yii::log("Vrijeme je ".$termin->vrijeme,"info","TerminController::actionIndex");
		$termin->idwiedervorlage0->idstranke0->attributes=$_GET['Stranka'];
	
	}
	$this->render('index',array(
		'termin'=>$termin,	
	));
}
public function actionView($id)
{
	$model=Termin::model()->findByPk($id);
	$komentar=new KomWv();
	$mot=new MaklerOwnsTermin();
	$komentar->idwiedervorlage=$model->idwiedervorlage;
	$criteria=new CDbCriteria();
	$criteria->compare('idwiedervorlage',$model->idwiedervorlage,true);
	$criteria->limit=5;
	$dataProvider=new CActiveDataProvider('KomWv',array(
			'criteria'=>$criteria,
			'sort'=>array(
					'defaultOrder'=>'datum DESC',
			),
			'pagination'=>array(
					'pageSize'=>5,
			)
	
	));
   if($model!=null)
   {
	$this->render('view',array(
			'model'=>$model,
			'komentar'=>$komentar,
			'dataProvider'=>$dataProvider,
			'mot'=>$mot,
	));
   }
   else
   {
   	throw new CHttpException(400,"Stranica ne postoji");
   }
}
public function actionGetTerminsForMakler($idmakler)
{
	if(isset($_GET['month']) && isset($_GET['year']))
	{
		$monthBegin=DateHelper::getBeginningOfMonth($_GET['month'], $_GET['year']);
		$monthEnd=DateHelper::getEndOfMonth($_GET['month'],$_GET['year']);
		$criteria=new CDbCriteria();
		$criteria->with=array('assignedMakler');
		$criteria->compare('assignedMakler.idmakler',$idmakler);
		$criteria->together=true;
		$termins=Termin::model()->findAll($criteria);
		$jsonArray=array();
		foreach($termins as $termin)
		{
			$json['title']=$termin->idwiedervorlage0->idstranke0->imeStranke." ".
					$termin->idwiedervorlage0->idstranke0->prezimeStranke;
			$json['url']=Yii::app()->createUrl("termin/view",array("id"=>$termin->idtermin));
			$dateTime=DateTime::createFromFormat("Y-m-d H:i:s", $termin->vrijeme);
			$json['date']=$dateTime->format("Y-m-d");
			$json['time']=$dateTime->format("H:i");
			array_push($jsonArray, $json);
		}
		echo json_encode($jsonArray);
	}
}
public function actionGetTerminsForZaposlenik($idkorisnik)
{
	if(isset($_GET['month']) && isset($_GET['year']))
	{
		$monthBegin=DateHelper::getBeginningOfMonth($_GET['month'], $_GET['year']);
		$monthEnd=DateHelper::getEndOfMonth($_GET['month'],$_GET['year']);
		$criteria=new CDbCriteria();
		$criteria->with=array('idwiedervorlage0');
		$criteria->together=true;
		$criteria->compare('idwiedervorlage0.idkorisnik',$idkorisnik);
		$termins=Termin::model()->findAll($criteria);
		$jsonArray=array();
		foreach($termins as $termin)
		{
			$json['title']=$termin->status;
			$json['url']=Yii::app()->createUrl("termin/view",array("id"=>$termin->idtermin));
			$dateTime=DateTime::createFromFormat("Y-m-d H:i:s", $termin->vrijeme);
			$json['date']=$dateTime->format("Y-m-d");
			$json['time']=$dateTime->format("H:i");
			array_push($jsonArray, $json);
		}
		echo json_encode($jsonArray);
	}
}
public function actionPomjeriTermin($id)
{
    $termin=Termin::model()->findByPk($id);
    if(isset($_POST['Termin']))
    {
        $termin->attributes=$_POST['Termin'];
       if($termin->save())
       {
          $this->redirect(array('termin/view','id'=>$termin->idtermin));          
       }
}
      $this->render("pomjeriVrijeme",array(
          'termin'=>$termin,
      ));
}
public function actionGetTermins()
{
	if(isset($_GET['month']) && isset($_GET['year']))
	{
		$monthBegin=DateHelper::getBeginningOfMonth($_GET['month'], $_GET['year']);
		$monthEnd=DateHelper::getEndOfMonth($_GET['month'],$_GET['year']);
		$criteria=new CDbCriteria();
		$criteria->with=array('idwiedervorlage0');
		$criteria->order='t.vrijeme';
		$criteria->together=true;
		//$criteria->compare('idwiedervorlage0.idkorisnik',$idkorisnik);
		$termins=Termin::model()->findAll($criteria);
		$jsonArray=array();
		foreach($termins as $termin)
		{
			$json['text']=$termin->idwiedervorlage0->idstranke0->imeStranke." ".
					$termin->idwiedervorlage0->idstranke0->prezimeStranke;
			$json['status']=$termin->status;
			$json['url']=Yii::app()->createUrl("termin/view",array("id"=>$termin->idtermin));
			$dateTime=DateTime::createFromFormat("Y-m-d H:i:s", $termin->vrijeme);
			$json['date']=$dateTime->format("Y-m-d");
			$json['time']=$dateTime->format("H:i");
			array_push($jsonArray, $json);
		}
		echo json_encode($jsonArray);
	}
}
public function actionCancel()
{
	if(isset($_POST['id']))
	{
		$id=$_POST['id'];
		
	$termin=Termin::model()->findByPk($id);
	$termin->status="absage";
	$termin->save();
        if($termin->isMaklerAssigned())
        {
            
        $mot=  MaklerOwnsTermin::model()->find("idtermin=?",array($termin->idtermin));
         $notifikacija=new Notifikacija();
                       $terminLink=  CHtml::link(Yii::t("main", "TERMIN"),array(
                           "termin/view",
                           'id'=>$mot->idtermin
                       ));
                       $notifikacija->text=Yii::t("main","TERMIN_OTKAZAN_NOTIFIKACIJA",array(
                           '{terminLink}'=>$terminLink,
                       ));
                       $notifikacija->idkorisnik=$mot->makler->idkorisnik;
                       $notifikacija->pregledano=0;
                       $notifikacija->save();
        }
	}
}
public function actionConfirm()
{
	
	if(isset($_POST['id']))
	{
		$id=$_POST['id'];
		$terminBestetig=new Terminbestitig();
		$termin=Termin::model()->findByPk($id);
		$terminBestetig->idtermin=$id;
		$transaction=Yii::app()->db->beginTransaction();
		try
		{
			if(!$terminBestetig->save(false))
				throw new Exception("yeah..");
			$termin->status="bestätigt";
                        $termin->idwiedervorlage0->status="bestätigt";
			if(!$termin->save(false))
				throw new Exception("ok...");
			$transaction->commit();
		}
		catch(Exception $e)
		{
			$transaction->rollback();
			Yii::log($e->getTraceAsString());
			
		}
	}
}
public function actionAssignMakler()
{
	$json=array();
	if(isset($_POST ['MaklerOwnsTermin']))
	{
		$mot=new MaklerOwnsTermin('create');
        $mot->attributes=$_POST['MaklerOwnsTermin'];
		if($mot->save())
		{
			$json['success']=true;
			$json['linkUrl']=Yii::app()->createUrl('makler/view',array('id'=>$mot->idmakler));
			$json['linkText']=$mot->makler->idkorisnik0->korisnickoIme;
                        $notifikacija=new Notifikacija();
                       $terminLink=  CHtml::link(Yii::t("main", "TERMIN"),array(
                           "termin/view",

protected/views/termin/assignMaklerDialog.php
<?php
Yii::app()->bootstrap->registerPlugin("notify");
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl."/js/maklerSelection.js",
		CClientScript::POS_HEAD);
new JsTrans("main", "bs");
$select2Url=Yii::app()->assetManager->publish(Yii::getPathOfAlias("ext.select2"));
Yii::app()->clientScript->registerScriptFile($select2Url."/select2.js");
Yii::app()->clientScript->registerCssFile($select2Url."/select2.css");
$this->beginWidget("zii.widgets.jui.CJuiDialog",array(
		'id'=>'assignMaklerDialog',
		'options'=>array(
				'autoOpen'=>false,
				'modal'=>true,
				'width'=>400,
				'height'=>300,
				'show'=>array(
						'effect'=>'fadeIn',
						'duration'=>500,
					),
				'hide'=>array(
						'effect'=>'explode',
						'duration'=>500,
				)
)
)); ?>
 <?php $form= $this->beginWidget("CActiveForm",array(
 		'enableAjaxValidation'=>true,
 		'id'=>'formica_mala',
 ));?>
 <div class="offset1 row">
 <?php echo CHtml::activeLabel($mot, "idmakler");?>
 <?php echo CHtml::activeTextField($mot, "idmakler",array(
 		"id"=>"idmaklerSelect",
 		
 		
 ));?>
 <?php echo $form->error($mot,"idmakler",array('style'=>'margin-top:10px; margin-bottom:10px;'));?>
 </div>
 <br/>
 <?php echo CHtml::activeHiddenField($mot,"idtermin",array("value"=>$model->idtermin));
 ?>
 <?php $this->widget("bootstrap.widgets.TbButton",array(
 		'type'=>'primary',
 		'label'=>Yii::t("main","DODIJELI_MAKLERA"),
 		'buttonType'=>'ajaxButton',
 		'url'=>Yii::app()->createUrl("termin/assignMakler"),
 		'ajaxOptions'=>array(
 				'type'=>'POST',
				'dataType'=>'json',
				'success'=>'js:displayErrorsOrNotifications',

 ),
		'htmlOptions'=>array(
				'class'=>'offset1',
				)
 ));?>
 <?php $this->endWidget();?>
 <?php $this->endWidget();?>
 <?php
 Yii::app()->clientScript->registerScript("allMaklers","var allMaklers=".
 json_encode(Makler::allMaklersArray()),CClientScript::POS_HEAD);
 ?>
 <script>

 </script>

protected/views/termin/commentView.php
<div class="comment">
<div class="author">
<?php echo $data->idwiedervorlage0->idkorisnik0->korisnickoIme;?>
<?php $img=CHtml::image(Yii::app()->baseUrl."/images/delete.png",'',array(
		'style'=>'width:8px;height:8px;'
));
   echo CHtml::ajaxLink("Löschen", array('komWv/delete'),
   		array(
		'type'=>'POST',
   		'data'=>array('id'=>$data->idkom_wv),
		 'success'=>'function(){$.fn.yiiListView.update("comments-list",{});
}',
),array(
	'class'=>'pull-right action-delete',
	'confirm'=>'Löschen?',
	'id'=>$data->idkom_wv,
)
   		);
?>
</div>

<div class="time">
<?php echo DateTime::createFromFormat("Y-m-d H:i:s",$data->datum)->format('d.M.Y H:i');
?>
</div>
<div class="comment-content">
<?php echo CHtml::encode($data->text);?>
</div>
</div>
<?php  Yii::app()->clientScript->registerScript('reinstall_links_after_ajax',
'$(document).ajaxComplete(function(){
				$(".action-delete").unbind("click");
		$(".action-delete").live("click",function(e){
		e.preventDefault();
		var self=$(this);
		if(confirm("Löschen?"))
		{
		$.ajax({
		type:"POST",
		data:{
		id:self.attr("id"),
		},
   		success:function(){
   		$.fn.yiiListView.update("comments-list",{});
   		},
   		url:"'.Yii::app()->createUrl("komWv/delete").'"
   		
		});
		}
		});
		});'
);?>

protected/views/termin/index.php
<?php
/* @var $this TerminController */
?>
<h1><?php echo Yii::t("main","SVI_TERMINI");?></h1>
<?php $this->widget('application.components.TerminGridWidget',array(
		'termin'=>$termin,
		'dataProvider'=>$termin->search(),
		'showMaklerColumn'=>true,
));?>

protected/views/termin/interestedMaklersView.php
<div class="makler_list_item" data-isMaklerAssigned="<?echo $isMaklerAssigned;?>">
<?php
echo CHtml::link($data->makler->idkorisnik0->korisnickoIme,
		array('makler/view','id'=>$data->idmakler));
?>
    <br>
    <b>"</b><?php echo $data->komentar ; ?><b>"</b>
    <hr/>
<?php CHtml::link(Yii::t("main","DODIJELI_TERMIN"),array("#"),array(
					'id'=>$data->idmakler,
					'class'=>'assignMaklerLink',
					'data-idtermin'=>$data->idtermin,
					'data-username'=>$data->makler->idkorisnik0->korisnickoIme,
));
?>
</div>

<script>
</script>

protected/views/termin/pomjeriVrijeme.php
<?php
Yii::setPathOfAlias("bootstrap", Yii::getPathOfAlias("ext.bootstrap"));
$form=$this->beginWidget("bootstrap.widgets.TbActiveForm",array(
    'id'=>'pomjeriVrijeme-form',
    'htmlOptions'=>array(
        'class'=>'well',
    )
));
?>
<?php echo $form->datetimepickerRow($termin,"vrijeme",array(
    'placeholder'=>Yii::t("main","TERMIN_NOVO_VRIJEME"),
    'class'=>'input-medium',
   // 'prepend'=>'<i class="icon-calendar"> </i>',
)); ?>
<?php echo $form->datetimepickerRow($termin,'rok_za_potvrdu',array(
    'class'=>'input-medium',
        //'prepend'=>'<i class="icon-calendar"> </i>',
)); ?>
<?php $this->widget("bootstrap.widgets.TbButton",array(
   'buttonType'=>'submit',
    'type'=>'primary',
    'label'=>Yii::t("main","SPREMI"),
    'htmlOptions'=>array(
        'style'=>'margin-left:10px;',
    )
    
));
?>
<?php $this->endWidget("bootstrap.widgets.TbActiveForm"); ?>

protected/views/termin/view.php
<?php
Yii::setPathOfAlias("bootstrap",
Yii::getPathOfAlias('application.extensions.bootstrap'));
new JsTrans("main","bs");
?>
<?php Yii::app()->clientScript->registerScript("assign_makler_script",
"var assignMaklerUrl='".Yii::app()->createUrl("termin/assignMakler")."';",
CClientScript::POS_HEAD);
new JsTrans("main", "de");
?>
<div class="row">
    <?php
$this->widget(
        'bootstrap.widgets.TbButtonGroup', 
        array(
            'size'=>'small',
            'type'=>'info',
            'htmlOptions'=>array(
				'class'=>'pull-left',
            		'style'=>'margin:10px;'
				),
            'buttons'=> array(
                array(
		'type'=>'info',
                    'visible'=>(Yii::app()->user->isAdmin() || Yii::app()->user->tip=="posrednik") &&
                                $model->assignedMakler==null,
		'label'=>Yii::t("main","DODIJELI_MAKLERA"),
		'buttonType'=>'button',
		'htmlOptions'=>array(
				'id'=>'displayDialogButton',
                    ),
                    ),
                 array(
                     'label'=>Yii::t("main","OBRISI_TERMIN"),
                     'visible'=>$model->currentUserIsAuthor() || Yii::app()->user->tip=="admin",
                     'url'=>'#','buttonType'=>'button',
                     'htmlOptions'=>array(
                         'id'=>'deleteButton',
                         'class'=>'deleteButton'
                         ),
                     
                     ),
                array(
                'label'=>'',
                    'visible'=>$model->currentUserIsAuthor() || Yii::app()->user->tip=="admin",
                'items'=>array(
                    
                    array('label'=>Yii::t("main","POMJERI_TERMIN"), 'url'=>array('pomjeriTermin', 'id'=>$model->idtermin)),
                    array('label'=>Yii::t("main","AZURIRAJ"),'url'=>array('wiedervorlage/update','id'=>$model->idwiedervorlage0->idwiedervorlage)),
                   
                    

                    '---',
                    
                ),
            ),
                
           ),
        )
        );
$deleteUrl=Yii::app()->createUrl("termin/delete",array('id'=>$model->idtermin));
$redirectUrl=Yii::app()->createUrl("termin/index");
Yii::app()->clientScript->registerScript("deleteURLs"," var deleteUrl='".$deleteUrl."';".
        "var redirectUrl='".$redirectUrl."';",
        CClientScript::POS_HEAD);

?>
    <script>
        $(function(){
    $(".deleteButton").click(function(e){
        e.preventDefault();
       if(confirm('Löschen?'))
       {
           $.ajax({
              url:deleteUrl,
              type:"POST",
              success:function()
              {
               location.assign(redirectUrl);
              }
           });
       }
       return false;
    });
    });
    </script>
</div>
<div class="row termin-view-wrapper">

<div class="span5 offset1">
    
<?php

$this->widget('bootstrap.widgets.TbDetailView',array(
		'type'=>'bordered stripped',
		'data'=>$model,
		'attributes'=>array(
				array(
						'label'=>Yii::t("main","VRIJEME_TERMINA"),
						'value'=>DateTime::createFromFormat("Y-m-d H:i:s", $model->vrijeme)->format("d.m.Y H:i"),
					
		),
					array(
						'label'=>Yii::t("main","ROK_ZA_POTVRDU"),
						'value'=>DateTime::createFromFormat("Y-m-d H:i:s", $model->rok_za_potvrdu)->format("d.m.Y H:i"),
						'visible'=>$model->status=="offen" && !Yii::app()->user->isMakler(),
							),
					
				array(
						'label'=>Yii::t("main","AUTOR"),
						'value'=>$model->idwiedervorlage0->idkorisnik0->korisnickoIme,
						'type'=>'raw',
						'visible'=>Yii::app()->user->isAdmin(),
		),
                    array(
                        'label'=>Yii::t("main","CIJENA"),
                        'value'=>$model->idwiedervorlage0->cijena,
                        'visible'=>Yii::app()->user->tip!="zaposlenik",
                    ),
				array(
					'label'=>Yii::t("main",Yii::t("main","STATUS")),
					'value'=>$model->status,
					'visible'=>Yii::app()->user->isAdmin(),	
				),
			array(
					'label'=>Yii::t("main","TIP_TERMINA"),
					'value'=>$model->idwiedervorlage0->idstranke0->pkv_vk,
					'visible'=>!Yii::app()->user->isMakler(),
		),
				array(
						'label'=>Yii::t("main","IME_STRANKE"),
						'value'=>$model->idwiedervorlage0->idstranke0->imeStranke,
                                     'visible'=>Yii::app()->user->tip!="makler" || $model->assignedToCurrentUser(),
						),
				array(
						'label'=>Yii::t("main","PREZIME_STRANKE"),
						'value'=>$model->idwiedervorlage0->idstranke0->prezimeStranke,
                                     'visible'=>Yii::app()->user->tip!="makler" || $model->assignedToCurrentUser(),
			),
				array(
						'label'=>Yii::t("main","ZANIMANJE_STRANKE"),
						'value'=>$model->idwiedervorlage0->idstranke0->zanimanjeStranke,
			),
				array(
						'label'=>Yii::t("main","GODISTE_STRANKE"),
						'value'=>$model->idwiedervorlage0->idstranke0->godisteStranke,
			),
			array(
					'label'=>Yii::t("main","ADRESA_STRANKE"),
					'value'=>$model->idwiedervorlage0->idstranke0->adresaStranke,
                                     'visible'=>Yii::app()->user->tip!="makler" || $model->assignedToCurrentUser(),
			),
                    array(
                        'label'=>Yii::t("main","TELEFON_STRANKE"),
                        'value'=>$model->idwiedervorlage0->idstranke0->telefonStranke,
                        'visible'=>Yii::app()->user->tip!="makler" || $model->assignedToCurrentUser(),
                    )
			
),
		'htmlOptions'=>array(
				'style'=>'margin:10px;',
				)
));

?>
</div>
<?php if(Yii::app()->user->isAdmin() || Yii::app()->user->tip=="posrednik"):?>
<div class="offset1 termin-maklers span3">
<div class="well span12">
<h4><?php echo Yii::t("main","MAKLER");?></h4>
<div id="assignedMaklerLink">
<?php if($model->assignedMakler!=null):?>
<?php echo CHtml::link($model->assignedMakler->makler->idkorisnik0->korisnickoIme,array(
		'makler/view',
		'id'=>$model->assignedMakler->idmakler,
));?>
    <?php $this->widget("bootstrap.widgets.TbButton",array(
        'size'=>'small',
        'type'=>'danger',
        'icon'=>'remove',
        'buttonType'=>'button',
        'htmlOptions'=>array(
            'id'=>'ponistiMakleraButton',
        )
    )); ?>
<?php endif;?>
</div>
</div>
<div class="well interested-maklers span12">
<h4><?php echo Yii::t("main","ZAINTERESOVANI_MAKLERI");?></h4>
<?php 
$this->widget('zii.widgets.CListView',array(
'id'=>'interestedMaklers-list',
'dataProvider'=>$model->interestedMaklersProvider(),
'itemView'=>'interestedMaklersView',
'viewData'=>array('isMaklerAssigned'=>$model->isMaklerAssignedString()),
'summaryText'=>'',
'enablePagination'=>true,
'htmlOptions'=>array(
'class'=>'pull-right',
)
))
?>
</div>
</div>
<?php  endif;?>
</div>

<?php if(Yii::app()->user->tip!="makler"):?>
<div class="form">

<?php $form = $this->beginWidget('CActiveForm',array(
		'id'=>'addComment-form',
		'enableAjaxValidation'=>false,
		'htmlOptions'=>array(),
));?>

    <table align="center">
        <tr>
            <td style="margin-left: 20px;" colspan="2">
<?php echo $form->textArea($komentar,'text',array(
		'id'=>'commentText',
		'rows'=>4,
		'cols'=>10,
		'maxlength'=>1000,
		'placeholder'=>Yii::t("main","UNESITE_KOMENTAR"),
		'style'=>'width:500px;margin-right:10px;'
));?>
            </td>
        </tr>
            <tr>
                <td style="width: 305px;"></td>
            <td>
<?php echo $form->hiddenField($komentar,'idwiedervorlage');?>
            
<?php echo CHtml::ajaxSubmitButton(Yii::t("main","SPREMI"),array('komWv/create'),array(
		'type'=>'POST',
		'beforeSend'=>'function(){}',
		'success'=>'function(data){
		$("#commentText").val("");
		$.fn.yiiListView.update("comments-list",{});
}',
));?>
            </td>
        </tr>
    </table>
    <?php $this->endWidget();?>
</div>
<?php $this->renderPartial("assignMaklerDialog",array('model'=>$model,'mot'=>$mot));?>

<?php $this->widget('zii.widgets.CListView',array(
		'id'=>'comments-list',
		'dataProvider'=>$dataProvider,
		'itemView'=>'commentView',
		'emptyText'=>Yii::t("main","NEMA_REZULTATA"),
		'enablePagination'=>true,
		'summaryText'=>'',
		'htmlOptions'=>array('style'=>'width:80%;margin-left:20%'),
));?>
<?php endif;?>
<?php Yii::app()->clientScript->registerScript("ponistiMakleraUrl","var ponistiMakleraUrl='".
        Yii::app()->createUrl("termin/ponistiMaklera",array("id"=>$model->idtermin))."';",  CClientScript::POS_HEAD); ?>
<script>
$(function(){
	$("#displayDialogButton").click(function(){
		$("#assignMaklerDialog").dialog("open");
	});
     $("#ponistiMakleraButton").click(function(e){
        e.preventDefault();
        if(confirm(Yii.t("main","PONISTI_MAKLERA_CONFIRM")))
        {
        $.ajax( {
            url:ponistiMakleraUrl,
            dataType:"GET",
           complete:function(response)
            {
                console.log("success pozvan");
                location.reload();
            }
        });
    }
     });

});
</script>